-- ============================================================
-- Stock Must-Fix #3 (atomic stock changes) + #4 (idempotency) - PHASE 1
--
-- PHASE 1 (this file): p_sale_id and p_fulfillment_event_id are both
-- OPTIONAL (default null). If the caller doesn't send one, the call
-- behaves exactly as it did before this migration - the dedupe claim is
-- skipped entirely and the stock source_reference is null - so the live
-- app (which doesn't send either id yet) keeps working unbroken the moment
-- this file runs. Once the JS that always sends both ids is deployed and
-- confirmed live, Phase 2 (a small separate file) makes both required.
--
-- Confirmed live bugs being fixed here:
-- 1. adjust_ungani_stock() and service_adjust_ungani_stock() both read
--    business_items.quantity with a plain SELECT, compute the new value in
--    PL/pgSQL, then UPDATE - a classic non-atomic check-then-act. Two
--    concurrent calls against the same item (two staff fulfilling the same
--    order line, or a POS sale racing an order fulfilment) can both read
--    the same starting quantity before either commits; the loser's UPDATE
--    silently overwrites the winner's result with a value computed from
--    stale data (a lost update).
-- 2. fulfill_ungani_order_item() has the identical read-then-write race on
--    ungani_order_items.fulfilled_quantity, AND - separately - increments
--    fulfilled_quantity before any dedupe check exists at all, so a retry
--    with the same fulfilment event id would double-count the line while
--    the stock side correctly reported "replay". Fixed by claiming the
--    fulfilment event id in its own log table FIRST, before
--    fulfilled_quantity changes at all, for every fulfilment regardless of
--    whether the line has a linked item or Stock Tracking is on.
-- 3. record_ungani_pos_sale() creates a brand-new invoice on every call, so
--    an invoice line's own id differs on every retry and can never be used
--    as a dedup key - a repeated Complete Sale click would create a second
--    invoice (and, for M-Pesa, send a second STK prompt) with no
--    protection at all. Fixed with an app-generated p_sale_id claimed in
--    its own log BEFORE the invoice is created.
-- 4. Nothing prevented the same logical event (a POS sale, an M-Pesa STK
--    callback, an order-fulfilment click) from being applied twice if the
--    RPC was called twice - no dedup existed at all before this migration.
-- 5. quantity/fulfilled_quantity being NULL (never initialized) made the
--    WHERE-clause guard evaluate to NULL instead of true/false, silently
--    rejecting a legitimate change with a false "not enough stock" error -
--    fixed with coalesce(..., 0) everywhere these are read.
--
-- Fix: every stock/fulfilment/sale mutation is a single atomic UPDATE
-- statement (no separate read), dedup log tables with unique constraints
-- make a retry with the same natural key an idempotent no-op, and failures
-- raise exceptions so Postgres's own rollback undoes everything from that
-- call automatically instead of relying on manual compensating updates.
--
-- Natural keys used per caller (never a generated sequence number, so a
-- genuine retry always carries the identical key). Each namespace is
-- prefixed so POS, M-Pesa, and fulfilment keys can never collide in
-- ungani_stock_movements.source_reference:
--   - POS sale (cash/mpesa_manual/mpesa alike): p_sale_id || ':' ||
--     line_index, generated by the app once when Complete Sale is pressed
--     and reused on retry - claimed in ungani_pos_sale_events BEFORE the
--     invoice is created, so a repeat click never creates a second invoice
--     or sends a second STK prompt.
--   - M-Pesa STK-confirmed sale (api/mpesa-stk-push.js, separate JS change
--     pending): 'mpesa:' || CheckoutRequestID || ':' || line_index - NOT
--     item_id, since the same item can appear on two lines of one sale and
--     item_id alone would collide, silently skipping the second line as a
--     false replay. Requires ORDER BY sort_order when fetching invoice
--     lines in that callback so line_index is stable across retries.
--   - Order fulfilment: 'fulfil:' || p_fulfillment_event_id, generated by
--     the app once when the Fulfil action starts and reused on any
--     automatic retry of that same click - claimed in
--     ungani_order_fulfillment_events before fulfilled_quantity changes at
--     all, whether or not the line has a linked item or Stock Tracking is
--     on.
--   - Manual adjustments (my-stock-tracking.html): source_reference stays
--     null - no dedupe, matches Chris's spec exactly
-- ============================================================

-- ============================================================
-- PART A: source_reference column + dedup index on ungani_stock_movements
-- ============================================================

alter table public.ungani_stock_movements
  add column if not exists source_reference text;

create unique index if not exists idx_ungani_stock_movements_source_ref
  on public.ungani_stock_movements (tenant_id, source_reference)
  where source_reference is not null;

-- ============================================================
-- PART B: adjust_ungani_stock - atomic + idempotent + distinct errors +
-- coalesce(quantity, 0). Restores the ungani_staff_can('items', 'edit')
-- check the live version has, which the first draft of this migration
-- dropped by mistake.
-- ============================================================

drop function if exists public.adjust_ungani_stock(uuid, text, numeric, text, numeric);

create or replace function public.adjust_ungani_stock(
  p_item_id uuid,
  p_movement_type text,
  p_quantity_delta numeric,
  p_reason text default null,
  p_reorder_level numeric default null,
  p_source_reference text default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_tenant_id uuid;
  v_clean_type text;
  v_quantity_before numeric;
  v_quantity_after numeric;
  v_reorder_level numeric;
  v_out_of_stock boolean;
  v_low_stock boolean;
  v_existing record;
begin
  v_tenant_id := public.get_my_ungani_tenant_id();

  if v_tenant_id is null then
    return jsonb_build_object('ok', false, 'message', 'No tenant workspace found.');
  end if;

  if not public.ungani_staff_can('items', 'edit') then
    return jsonb_build_object('ok', false, 'message', 'You do not have permission to adjust stock.');
  end if;

  if not public.can_write_ungani_client_data() then
    return jsonb_build_object('ok', false, 'message', 'This account is currently read-only.');
  end if;

  v_clean_type := lower(trim(coalesce(p_movement_type, '')));

  if v_clean_type not in ('restock', 'sale', 'adjustment', 'waste') then
    return jsonb_build_object('ok', false, 'message', 'Invalid movement type. Use restock, sale, adjustment, or waste.');
  end if;

  if p_quantity_delta is null or p_quantity_delta = 0 then
    return jsonb_build_object('ok', false, 'message', 'Quantity change must not be zero.');
  end if;

  -- Idempotent replay: a retry carrying the same source_reference returns
  -- the original outcome instead of re-applying the change or erroring.
  -- p_source_reference is null for manual adjustments and for any Phase 1
  -- caller that hasn't started sending an event id yet - both skip this
  -- block entirely, same as before this migration.
  if p_source_reference is not null then
    select * into v_existing
    from public.ungani_stock_movements
    where tenant_id = v_tenant_id and source_reference = p_source_reference;

    if found then
      return jsonb_build_object(
        'ok', true,
        'message', 'Already recorded (idempotent replay).',
        'quantity', v_existing.quantity_after,
        'replay', true
      );
    end if;
  end if;

  -- Single atomic statement - no prior SELECT, so two concurrent calls
  -- against the same item can never both compute from the same stale
  -- quantity. coalesce(quantity, 0) means a never-initialized quantity is
  -- treated as 0 rather than failing this guard with NULL >= 0 (which is
  -- NULL, not true). quantity_before is derived arithmetically from the
  -- returned new value (new = old + delta, so old = new - delta) rather
  -- than a separate read.
  update public.business_items
  set quantity = coalesce(quantity, 0) + p_quantity_delta,
      reorder_level = coalesce(p_reorder_level, reorder_level)
  where id = p_item_id
    and tenant_id = v_tenant_id
    and coalesce(quantity, 0) + p_quantity_delta >= 0
  returning quantity - p_quantity_delta, quantity, reorder_level
  into v_quantity_before, v_quantity_after, v_reorder_level;

  if not found then
    -- Distinguish "doesn't exist" from "not enough stock" - this extra
    -- check only runs on the failure path, so it never reintroduces a race
    -- on the success path above.
    if exists (select 1 from public.business_items where id = p_item_id and tenant_id = v_tenant_id) then
      return jsonb_build_object('ok', false, 'message', 'Not enough stock for this change.');
    else
      return jsonb_build_object('ok', false, 'message', 'Item not found.');
    end if;
  end if;

  begin
    insert into public.ungani_stock_movements (
      tenant_id, item_id, movement_type, quantity_delta, quantity_before, quantity_after, reason, source_reference, created_by
    )
    values (
      v_tenant_id, p_item_id, v_clean_type, p_quantity_delta, v_quantity_before, v_quantity_after,
      nullif(trim(coalesce(p_reason, '')), ''), p_source_reference, auth.uid()
    );
  exception
    when unique_violation then
      -- Lost the race between the replay check above and this insert -
      -- another concurrent call with the same source_reference committed
      -- first. Undo this call's business_items update and return the
      -- winner's recorded outcome instead of double-applying.
      update public.business_items
      set quantity = quantity - p_quantity_delta
      where id = p_item_id and tenant_id = v_tenant_id;

      select * into v_existing
      from public.ungani_stock_movements
      where tenant_id = v_tenant_id and source_reference = p_source_reference;

      return jsonb_build_object(
        'ok', true,
        'message', 'Already recorded (idempotent replay).',
        'quantity', v_existing.quantity_after,
        'replay', true
      );
  end;

  v_out_of_stock := v_quantity_after = 0;
  v_low_stock := (not v_out_of_stock) and v_reorder_level is not null and v_quantity_after <= v_reorder_level;

  return jsonb_build_object(
    'ok', true,
    'message', 'Stock adjusted.',
    'quantity', v_quantity_after,
    'reorder_level', v_reorder_level,
    'out_of_stock', v_out_of_stock,
    'low_stock', v_low_stock
  );
exception
  when others then
    return jsonb_build_object('ok', false, 'message', sqlerrm);
end;
$function$;

revoke all on function public.adjust_ungani_stock(uuid, text, numeric, text, numeric, text) from public, anon;
grant execute on function public.adjust_ungani_stock(uuid, text, numeric, text, numeric, text) to authenticated;

-- ============================================================
-- PART C: service_adjust_ungani_stock - same atomic + coalesce(quantity, 0)
-- treatment, for the service-role M-Pesa callback path. Live version has
-- no permission checks (correct - service-role only), so none are added.
-- ============================================================

drop function if exists public.service_adjust_ungani_stock(uuid, uuid, text, numeric, text);

create or replace function public.service_adjust_ungani_stock(
  p_tenant_id uuid,
  p_item_id uuid,
  p_movement_type text,
  p_quantity_delta numeric,
  p_reason text default null,
  p_source_reference text default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_quantity_before numeric;
  v_quantity_after numeric;
  v_reorder_level numeric;
  v_existing record;
begin
  if p_movement_type not in ('restock', 'sale', 'adjustment', 'waste') then
    return jsonb_build_object('ok', false, 'message', 'Invalid movement type.');
  end if;

  if p_quantity_delta is null or p_quantity_delta = 0 then
    return jsonb_build_object('ok', false, 'message', 'Quantity delta is required.');
  end if;

  if p_source_reference is not null then
    select * into v_existing
    from public.ungani_stock_movements
    where tenant_id = p_tenant_id and source_reference = p_source_reference;

    if found then
      return jsonb_build_object(
        'ok', true, 'message', 'Already recorded (idempotent replay).',
        'quantity', v_existing.quantity_after, 'replay', true
      );
    end if;
  end if;

  update public.business_items
  set quantity = coalesce(quantity, 0) + p_quantity_delta
  where id = p_item_id
    and tenant_id = p_tenant_id
    and coalesce(quantity, 0) + p_quantity_delta >= 0
  returning quantity - p_quantity_delta, quantity, reorder_level
  into v_quantity_before, v_quantity_after, v_reorder_level;

  if not found then
    if exists (select 1 from public.business_items where id = p_item_id and tenant_id = p_tenant_id) then
      return jsonb_build_object('ok', false, 'message', 'Not enough stock for this change.');
    else
      return jsonb_build_object('ok', false, 'message', 'Item not found.');
    end if;
  end if;

  begin
    insert into public.ungani_stock_movements (
      tenant_id, item_id, movement_type, quantity_delta, quantity_before, quantity_after, reason, source_reference
    )
    values (
      p_tenant_id, p_item_id, p_movement_type, p_quantity_delta, v_quantity_before, v_quantity_after, p_reason, p_source_reference
    );
  exception
    when unique_violation then
      update public.business_items
      set quantity = quantity - p_quantity_delta
      where id = p_item_id and tenant_id = p_tenant_id;

      select * into v_existing
      from public.ungani_stock_movements
      where tenant_id = p_tenant_id and source_reference = p_source_reference;

      return jsonb_build_object(
        'ok', true, 'message', 'Already recorded (idempotent replay).',
        'quantity', v_existing.quantity_after, 'replay', true
      );
  end;

  return jsonb_build_object(
    'ok', true, 'message', 'Stock adjusted.', 'quantity', v_quantity_after,
    'reorder_level', v_reorder_level,
    'out_of_stock', v_quantity_after = 0,
    'low_stock', v_reorder_level is not null and v_quantity_after <= v_reorder_level
  );
exception
  when others then
    return jsonb_build_object('ok', false, 'message', sqlerrm);
end;
$function$;

revoke all on function public.service_adjust_ungani_stock(uuid, uuid, text, numeric, text, text) from public, anon, authenticated;
grant execute on function public.service_adjust_ungani_stock(uuid, uuid, text, numeric, text, text) to service_role;

-- ============================================================
-- PART D: record_ungani_pos_sale - rewritten from the live definition
-- Chris pulled directly. p_sale_id is a 5th, OPTIONAL parameter (Phase 1) -
-- when null, the whole claim block is skipped and the function behaves
-- exactly as it does live today, including the per-line stock call (which
-- naturally gets source_reference = null, since p_sale_id || ':' ||
-- line_index evaluates to null when p_sale_id is null).
-- ============================================================

create table if not exists public.ungani_pos_sale_events (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  sale_id text not null,
  invoice_id uuid,
  result jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_ungani_pos_sale_events_dedup
  on public.ungani_pos_sale_events (tenant_id, sale_id);

alter table public.ungani_pos_sale_events enable row level security;

drop policy if exists ungani_pos_sale_events_tenant_select on public.ungani_pos_sale_events;
create policy ungani_pos_sale_events_tenant_select on public.ungani_pos_sale_events
  for select
  using (tenant_id = public.get_my_ungani_tenant_id());

revoke all on public.ungani_pos_sale_events from public, anon, authenticated;
grant select on public.ungani_pos_sale_events to authenticated;

drop function if exists public.record_ungani_pos_sale(text, uuid, text, jsonb);

create or replace function public.record_ungani_pos_sale(p_customer_name text, p_customer_person_id uuid DEFAULT NULL::uuid, p_payment_method text DEFAULT 'cash'::text, p_items jsonb DEFAULT '[]'::jsonb, p_sale_id text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_tenant_id uuid;
  v_package_key text;
  v_pos_included boolean;
  v_pos_enabled boolean;
  v_stock_tracking_enabled boolean;
  v_payment_method text;
  v_invoice_result jsonb;
  v_invoice_id uuid;
  v_invoice_number text;
  v_total_amount numeric;
  v_item jsonb;
  v_line_index int;
  v_stock_result jsonb;
  v_result jsonb;
  v_existing_result jsonb;
  v_has_sale_id boolean;
begin
  v_tenant_id := public.get_my_ungani_tenant_id();

  if v_tenant_id is null then
    return jsonb_build_object('ok', false, 'message', 'No tenant workspace found.');
  end if;

  if not public.can_write_ungani_client_data() then
    return jsonb_build_object('ok', false, 'message', 'This account is currently read-only.');
  end if;

  if not public.ungani_staff_can('money', 'create') then
    return jsonb_build_object('ok', false, 'message', 'You do not have permission to record sales.');
  end if;

  v_has_sale_id := p_sale_id is not null and trim(p_sale_id) != '';

  -- PHASE 1: dedupe is opt-in. When the client doesn't send a sale id yet
  -- (old JS, mid-rollout), this whole block is skipped and the call
  -- behaves exactly as it did before this migration. Once the new JS
  -- always sends one, Phase 2 makes this required.
  if v_has_sale_id then
    begin
      insert into public.ungani_pos_sale_events (tenant_id, sale_id)
      values (v_tenant_id, p_sale_id);
    exception
      when unique_violation then
        select result into v_existing_result
        from public.ungani_pos_sale_events
        where tenant_id = v_tenant_id and sale_id = p_sale_id;

        if v_existing_result is null then
          return jsonb_build_object('ok', false, 'message', 'This sale is already being processed - please check Money in a moment.');
        end if;

        return v_existing_result || jsonb_build_object('replay', true);
    end;
  end if;

  select stock_tracking_enabled, pos_enabled
  into v_stock_tracking_enabled, v_pos_enabled
  from public.tenants
  where id = v_tenant_id;

  if coalesce(v_pos_enabled, false) is not true then
    raise exception 'Point of Sale is not turned on for this business. Enable it in Settings.';
  end if;

  select package_key into v_package_key
  from public.ungani_subscriptions
  where tenant_id = v_tenant_id;

  select coalesce(p.pos_included, false) into v_pos_included
  from public.ungani_packages p
  where p.package_key = v_package_key;

  if coalesce(v_pos_included, false) is not true then
    raise exception 'Your package does not include Point of Sale. Upgrade to Business or Custom to use Quick Sale.';
  end if;

  v_payment_method := lower(trim(coalesce(p_payment_method, 'cash')));
  if v_payment_method not in ('cash', 'mpesa', 'mpesa_manual') then
    raise exception 'Invalid payment method.';
  end if;

  if jsonb_array_length(coalesce(p_items, '[]'::jsonb)) = 0 then
    raise exception 'Add at least one item to the sale.';
  end if;

  -- Raising here (rather than returning v_invoice_result directly) rolls
  -- back the sale-id claim above too (when one was made), so a corrected
  -- retry isn't permanently blocked by a failed attempt.
  v_invoice_result := public.owner_upsert_ungani_customer_invoice(
    p_customer_name := p_customer_name,
    p_customer_person_id := p_customer_person_id,
    p_items := p_items
  );

  if coalesce((v_invoice_result->>'ok')::boolean, false) is not true then
    raise exception '%', coalesce(v_invoice_result->>'message', 'Could not create invoice.');
  end if;

  v_invoice_id := (v_invoice_result->>'invoice_id')::uuid;

  select invoice_number, total_amount into v_invoice_number, v_total_amount
  from public.ungani_customer_invoices
  where id = v_invoice_id;

  if v_payment_method in ('cash', 'mpesa_manual') then
    -- source_reference is computed directly from p_sale_id and this loop's
    -- own index (null || ':' || n evaluates to null, so this is a no-op
    -- when no sale id was sent) - no invoice-line lookup needed at all.
    for v_item, v_line_index in
      select value, (ordinality - 1)::int
      from jsonb_array_elements(p_items) with ordinality as t(value, ordinality)
    loop
      if v_item->>'item_id' is not null and coalesce(v_stock_tracking_enabled, false) then
        v_stock_result := public.adjust_ungani_stock(
          (v_item->>'item_id')::uuid,
          'sale',
          -coalesce((v_item->>'quantity')::numeric, 1),
          'POS sale: ' || v_invoice_number,
          null,
          case when v_has_sale_id then p_sale_id || ':' || v_line_index else null end
        );

        if coalesce((v_stock_result->>'ok')::boolean, false) is not true then
          raise exception '%', coalesce(v_stock_result->>'message', 'Could not adjust stock.');
        end if;
      end if;
    end loop;

    perform public.record_ungani_invoice_payment(
      p_invoice_id := v_invoice_id,
      p_amount := v_total_amount,
      p_method := case when v_payment_method = 'mpesa_manual' then 'M-Pesa' else 'cash' end,
      p_notes := case when v_payment_method = 'mpesa_manual' then 'Quick Sale - customer paid M-Pesa directly' else 'Quick Sale' end
    );

    v_result := jsonb_build_object(
      'ok', true, 'invoice_id', v_invoice_id, 'invoice_number', v_invoice_number,
      'total_amount', v_total_amount, 'status', 'paid', 'payment_method', v_payment_method
    );
  else
    v_result := jsonb_build_object(
      'ok', true, 'invoice_id', v_invoice_id, 'invoice_number', v_invoice_number,
      'total_amount', v_total_amount, 'status', 'draft', 'payment_method', 'mpesa'
    );
  end if;

  if v_has_sale_id then
    -- Fill in the real outcome (and invoice_id) on the claim row so a later
    -- replay - after this call has already committed - returns the true
    -- original result instead of a placeholder.
    update public.ungani_pos_sale_events
    set invoice_id = v_invoice_id, result = v_result
    where tenant_id = v_tenant_id and sale_id = p_sale_id;
  end if;

  return v_result;
exception
  when others then
    return jsonb_build_object('ok', false, 'message', sqlerrm);
end;
$function$;

revoke all on function public.record_ungani_pos_sale(text, uuid, text, jsonb, text) from public, anon;
grant execute on function public.record_ungani_pos_sale(text, uuid, text, jsonb, text) to authenticated;

-- ============================================================
-- PART E: fulfill_ungani_order_item - full redesign, restoring the two
-- permission checks (ungani_staff_can('money','edit'),
-- can_write_ungani_client_data()) the live version has and this
-- migration's first draft dropped by mistake.
--
-- p_fulfillment_event_id is a 3rd, OPTIONAL parameter (Phase 1) - when
-- null (or blank), the claim block is skipped entirely and the call
-- behaves exactly as it does live today. A caller sending only 2 positional
-- args still works, since the 3rd parameter has a default.
--
-- fulfilled_quantity's own update is a single atomic statement whose WHERE
-- clause (fulfilled_quantity + p_fulfill_quantity <= quantity) makes it
-- structurally impossible for the result to exceed the ordered quantity -
-- a row that would exceed it simply doesn't match the WHERE clause, so the
-- UPDATE affects zero rows and the exception below fires instead of ever
-- writing an over-fulfilled value.
-- ============================================================

create table if not exists public.ungani_order_fulfillment_events (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  order_item_id uuid not null references public.ungani_order_items(id) on delete cascade,
  fulfillment_event_id text not null,
  fulfill_quantity numeric not null,
  result jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_ungani_order_fulfillment_events_dedup
  on public.ungani_order_fulfillment_events (tenant_id, fulfillment_event_id);

alter table public.ungani_order_fulfillment_events enable row level security;

drop policy if exists ungani_order_fulfillment_events_tenant_select on public.ungani_order_fulfillment_events;
create policy ungani_order_fulfillment_events_tenant_select on public.ungani_order_fulfillment_events
  for select
  using (tenant_id = public.get_my_ungani_tenant_id());

revoke all on public.ungani_order_fulfillment_events from public, anon, authenticated;
grant select on public.ungani_order_fulfillment_events to authenticated;

drop function if exists public.fulfill_ungani_order_item(uuid, numeric);
drop function if exists public.fulfill_ungani_order_item(uuid, numeric, text);

create or replace function public.fulfill_ungani_order_item(p_order_item_id uuid, p_fulfill_quantity numeric, p_fulfillment_event_id text default null)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_tenant_id uuid;
  v_stock_tracking_enabled boolean;
  v_line record;
  v_new_fulfilled numeric;
  v_stock_result jsonb;
  v_total_ordered numeric;
  v_total_fulfilled numeric;
  v_new_order_status text;
  v_result jsonb;
  v_existing_result jsonb;
  v_has_event_id boolean;
begin
  v_tenant_id := public.get_my_ungani_tenant_id();

  if v_tenant_id is null then
    return jsonb_build_object('ok', false, 'message', 'No tenant workspace found.');
  end if;

  if not public.ungani_staff_can('money', 'edit') then
    return jsonb_build_object('ok', false, 'message', 'You do not have permission to fulfil orders.');
  end if;

  if not public.can_write_ungani_client_data() then
    return jsonb_build_object('ok', false, 'message', 'This account is currently read-only.');
  end if;

  if p_fulfill_quantity is null or p_fulfill_quantity <= 0 then
    return jsonb_build_object('ok', false, 'message', 'Fulfil quantity must be greater than zero.');
  end if;

  select oi.id, oi.order_id, oi.item_id, oi.quantity, o.status, o.order_number
  into v_line
  from public.ungani_order_items oi
  join public.ungani_orders o on o.id = oi.order_id
  where oi.id = p_order_item_id and oi.tenant_id = v_tenant_id;

  if v_line.id is null then
    return jsonb_build_object('ok', false, 'message', 'Order line not found.');
  end if;

  if v_line.status not in ('confirmed', 'partially_fulfilled') then
    return jsonb_build_object('ok', false, 'message', 'This order must be confirmed before it can be fulfilled.');
  end if;

  v_has_event_id := p_fulfillment_event_id is not null and trim(p_fulfillment_event_id) != '';

  -- PHASE 1: dedupe is opt-in. When the client doesn't send an event id yet
  -- (old JS, mid-rollout), this is skipped entirely and the call behaves
  -- exactly as it did before this migration - just without dedupe
  -- protection. Once the new JS always sends one, Phase 2 makes this
  -- required. When it IS sent, claiming it FIRST - before
  -- fulfilled_quantity changes at all - protects every fulfilment
  -- regardless of whether the line has a linked item or Stock Tracking is
  -- on, which a stock-movements-only dedupe could never reach on its own.
  if v_has_event_id then
    insert into public.ungani_order_fulfillment_events (
      tenant_id, order_item_id, fulfillment_event_id, fulfill_quantity
    )
    values (
      v_tenant_id, p_order_item_id, p_fulfillment_event_id, p_fulfill_quantity
    );
  end if;

  -- Single atomic statement - no prior SELECT of fulfilled_quantity, so two
  -- concurrent fulfil calls on the same line can never both compute from
  -- the same stale value. The WHERE clause makes exceeding the ordered
  -- quantity structurally impossible: a row that would exceed it doesn't
  -- match, so this affects zero rows and the exception below fires instead
  -- of ever writing an over-fulfilled value. coalesce(fulfilled_quantity,
  -- 0) treats a never-initialized value as 0 rather than failing on NULL.
  update public.ungani_order_items
  set fulfilled_quantity = coalesce(fulfilled_quantity, 0) + p_fulfill_quantity
  where id = p_order_item_id
    and tenant_id = v_tenant_id
    and coalesce(fulfilled_quantity, 0) + p_fulfill_quantity <= quantity
  returning fulfilled_quantity
  into v_new_fulfilled;

  if not found then
    -- Raising here (rather than a manual compensating update) rolls back
    -- the fulfilment-event claim above automatically (when one was made),
    -- so a corrected retry under the same event id is never permanently
    -- blocked.
    raise exception 'That would fulfil more than was ordered on this line.';
  end if;

  select stock_tracking_enabled into v_stock_tracking_enabled
  from public.tenants where id = v_tenant_id;

  if v_line.item_id is not null and coalesce(v_stock_tracking_enabled, false) then
    v_stock_result := public.adjust_ungani_stock(
      v_line.item_id, 'sale', -p_fulfill_quantity, 'Order fulfillment: ' || v_line.order_number,
      null, case when v_has_event_id then 'fulfil:' || p_fulfillment_event_id else null end
    );

    if coalesce((v_stock_result->>'ok')::boolean, false) is not true then
      -- Raising here rolls back both the fulfilled_quantity update above
      -- and the fulfilment-event claim (when one was made), in one
      -- automatic step.
      raise exception '%', coalesce(v_stock_result->>'message', 'Could not adjust stock.');
    end if;
  end if;

  select coalesce(sum(quantity), 0), coalesce(sum(fulfilled_quantity), 0)
  into v_total_ordered, v_total_fulfilled
  from public.ungani_order_items
  where order_id = v_line.order_id;

  v_new_order_status := case
    when v_total_fulfilled >= v_total_ordered then 'fulfilled'
    when v_total_fulfilled > 0 then 'partially_fulfilled'
    else v_line.status
  end;

  update public.ungani_orders
  set status = v_new_order_status, updated_at = now()
  where id = v_line.order_id;

  v_result := jsonb_build_object(
    'ok', true,
    'fulfilled_quantity', v_new_fulfilled,
    'order_status', v_new_order_status
  );

  if v_has_event_id then
    -- Fill in the real outcome on the claim row so a later replay (after
    -- this call has already committed) returns the true original result
    -- instead of a placeholder.
    update public.ungani_order_fulfillment_events
    set result = v_result
    where tenant_id = v_tenant_id and fulfillment_event_id = p_fulfillment_event_id;
  end if;

  return v_result;
exception
  when unique_violation then
    -- The fulfilment-event insert lost a race (or this is a plain retry) -
    -- nothing else in this call has touched real data yet, since the claim
    -- is the very first write. Return the original outcome instead of
    -- re-applying.
    select result into v_existing_result
    from public.ungani_order_fulfillment_events
    where tenant_id = v_tenant_id and fulfillment_event_id = p_fulfillment_event_id;

    if v_existing_result is null then
      -- The original call claimed the id but hasn't finished yet (a true
      -- millisecond-level race, not a simple double-click) - there is no
      -- recorded outcome to replay.
      return jsonb_build_object('ok', false, 'message', 'This fulfilment is already being processed - please check the order in a moment.');
    end if;

    return v_existing_result || jsonb_build_object('replay', true);
  when others then
    return jsonb_build_object('ok', false, 'message', sqlerrm);
end;
$function$;

revoke all on function public.fulfill_ungani_order_item(uuid, numeric, text) from public, anon;
grant execute on function public.fulfill_ungani_order_item(uuid, numeric, text) to authenticated;

-- ============================================================
-- COMBINED VERIFICATION SELECT
-- Every *_overload_count should be exactly 1, every *_exists should be at
-- least 1, and every *_anon_exec / *_authenticated_write must be false.
-- ============================================================

select
  (select count(*) from pg_proc where proname = 'adjust_ungani_stock') as adjust_ungani_stock_overload_count,
  (select count(*) from pg_proc where proname = 'service_adjust_ungani_stock') as service_adjust_ungani_stock_overload_count,
  (select count(*) from pg_proc where proname = 'fulfill_ungani_order_item') as fulfill_ungani_order_item_overload_count,
  (select count(*) from pg_proc where proname = 'record_ungani_pos_sale') as record_ungani_pos_sale_overload_count,
  (select count(*) from information_schema.columns where table_name = 'ungani_stock_movements' and column_name = 'source_reference') as source_reference_column_exists,
  (select count(*) from pg_indexes where indexname = 'idx_ungani_stock_movements_source_ref') as stock_movements_unique_index_exists,
  (select count(*) from pg_tables where schemaname = 'public' and tablename = 'ungani_pos_sale_events') as pos_sale_events_table_exists,
  (select count(*) from pg_indexes where indexname = 'idx_ungani_pos_sale_events_dedup') as pos_sale_events_unique_index_exists,
  (select count(*) from pg_tables where schemaname = 'public' and tablename = 'ungani_order_fulfillment_events') as fulfillment_events_table_exists,
  (select count(*) from pg_indexes where indexname = 'idx_ungani_order_fulfillment_events_dedup') as fulfillment_events_unique_index_exists,
  has_function_privilege('anon', 'public.adjust_ungani_stock(uuid, text, numeric, text, numeric, text)', 'execute') as adjust_ungani_stock_anon_exec,
  has_function_privilege('anon', 'public.service_adjust_ungani_stock(uuid, uuid, text, numeric, text, text)', 'execute') as service_adjust_ungani_stock_anon_exec,
  has_function_privilege('anon', 'public.record_ungani_pos_sale(text, uuid, text, jsonb, text)', 'execute') as record_ungani_pos_sale_anon_exec,
  has_function_privilege('anon', 'public.fulfill_ungani_order_item(uuid, numeric, text)', 'execute') as fulfill_ungani_order_item_anon_exec,
  has_table_privilege('anon', 'public.ungani_pos_sale_events', 'select') as pos_sale_events_anon_select,
  has_table_privilege('authenticated', 'public.ungani_pos_sale_events', 'insert') as pos_sale_events_authenticated_insert,
  has_table_privilege('anon', 'public.ungani_order_fulfillment_events', 'select') as fulfillment_events_anon_select,
  has_table_privilege('authenticated', 'public.ungani_order_fulfillment_events', 'insert') as fulfillment_events_authenticated_insert;
